version: "3"
services:
  db:
    image: mariadb
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      MYSQL_ROOT_HOST: db
      MYSQL_DATABASE: lelc2
      MYSQL_TEST_DATABASE: lelc2_test
    ports:
      - "3307:3306"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      MYSQL_ROOT_HOST: db
      MYSQL_DATABASE: lelc2
      MYSQL_TEST_DATABASE: lelc2_test
    volumes:
      - .:/lelc2
      - ./config/database.yml.docker:/lelc2/config/database.yml
      - ${SSH_PATH}:/home/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
