source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
#gem 'sqlite3'
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# gem 'jquery-turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc




group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'rspec-rails', '~> 3.0.0'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'grb'
end


gem 'responders', '~> 2.0'

gem 'haml'
gem 'will_paginate'
gem "breadcrumbs_on_rails"

gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'less-rails-bootstrap'


gem 'ckeditor'
gem 'non-stupid-digest-assets'#, '~> 1.0.4'

#gem 'fullcalendar-rails'
#gem 'momentjs-rails'
gem 'rails4-autocomplete'

gem 'chronic'
gem 'cancancan', '~> 1.10'
gem 'ancestry'
#gem 'awesome_nested_set'
gem 'acts_as_list'

gem "audited-activerecord"
#gem "audited", "~> 4.0"
gem "aasm"

gem 'jquery.fileupload-rails'
#gem "jquery-fileupload-rails"

gem 'i18n'#, '0.6.9'
gem 'globalize', '~> 5.0.0'
gem 'globalize-accessors'

# gem 'prawn'
# gem 'prawn-table'

# gem "chartkick"
#https://github.com/ankane/groupdate: need to run on the command line of the server: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql
# gem 'groupdate'

#http://fullscreen.github.io/squid/
# gem 'squid', '~> 1.2'
# gem 'redcarpet'
# gem 'imgkit'
#gem 'wkhtmltoimage-binary'
#gem 'rmagick'

# gem 'acts-as-taggable-on', '~> 4.0'

gem 'remotipart', '~> 1.2'

gem 'rack-cors', :require => 'rack/cors'

# gem 'sendgrid-ruby', '6.0.0'
